const svg = document.getElementById("topology");
const list = document.getElementById("deviceList");
const selection = document.getElementById("selection");
const pingBtn = document.getElementById("pingBtn");
const agentBtn = document.getElementById("agentBtn");
const agentStatus = document.getElementById("agentStatus");
const parentField = document.getElementById("parentField");
const connectBtn = document.getElementById("connectBtn");
const canvasWrap = document.getElementById("canvasWrap");
const zoomLabel = document.getElementById("zoomLabel");
const deviceInspector = document.getElementById("deviceInspector");
const inspectorContent = document.getElementById("inspectorContent");
const serverStartBtn = document.getElementById("serverStartBtn");
const serverStopBtn = document.getElementById("serverStopBtn");
const serverStatus = document.getElementById("serverStatus");
const cloudStatus = document.getElementById("cloudStatus");
const cloudConnectionDot = document.getElementById("cloudConnectionDot");
const cloudConnectionState = document.getElementById("cloudConnectionState");
const cloudApiKey = document.getElementById("cloudApiKey");
const cloudSaveBtn = document.getElementById("cloudSaveBtn");
const layout = document.querySelector(".layout");
const topologyScreenBtn = document.getElementById("topologyScreenBtn");
const managementScreenBtn = document.getElementById("managementScreenBtn");
layout.classList.add("mode-topology");
const STORAGE = "gss-network-lab-v2";
let zoom=0.1;
if(!window.gssLab){window.gssLab={ping:async(host)=>/^10\./.test(host)?({ok:true,latencyMs:1+Math.floor(Math.random()*4),output:"GSS virtual ICMP reply"}):({ok:false,error:"Browser preview has no native ICMP bridge"}),startLocalServer:async()=>({ok:true,url:location.origin}),stopLocalServer:async()=>({ok:true}),loadInfrastructure:async()=>({devices:[],links:[]}),saveInfrastructure:async()=>({ok:true}),cloudStatus:async()=>({configured:false,state:"preview",message:"Cloud sync is available in the Electron app."}),configureCloud:async()=>({ok:false,error:"Cloud sync is available in the Electron app."}),onTraffic:()=>{},onCloudStatus:()=>{}};}

function makeSeed() {
  const devices = [
    ["gss-server","GSS Main Server","Server","10.0.0.10","HQ",690,80],["asa-hq","ASA-01 Firewall","Firewall","10.0.0.1","HQ",690,200],["router-core","CORE-2911","Router","10.0.0.2","HQ",690,330],["switch-core","CORE-2960","Switch","10.0.0.3","HQ",690,460],
    ["router-kawempe","Kawempe Router","Router","10.0.1.1","Kawempe",240,210],["switch-kawempe","Kawempe Switch","Switch","10.0.1.2","Kawempe",240,365],["router-nansana","Nansana Router","Router","10.0.2.1","Nansana",1140,210],["switch-nansana","Nansana Switch","Switch","10.0.2.2","Nansana",1140,365],
    ["router-masaka","Masaka Router","Router","10.0.3.1","Masaka",270,650],["switch-masaka","Masaka Switch","Switch","10.0.3.2","Masaka",270,790],["router-ntinda","Ntinda Router","Router","10.0.4.1","Ntinda",1110,650],["switch-ntinda","Ntinda Switch","Switch","10.0.4.2","Ntinda",1110,790]
  ].map(([id,name,type,ip,site,x,y]) => ({id,name,type,ip,site,x,y,status:"online"}));
  const links = [["gss-server","asa-hq"],["asa-hq","router-core"],["router-core","switch-core"],["switch-core","router-kawempe"],["switch-core","router-nansana"],["switch-core","router-masaka"],["switch-core","router-ntinda"],["router-kawempe","switch-kawempe"],["router-nansana","switch-nansana"],["router-masaka","switch-masaka"],["router-ntinda","switch-ntinda"]];
  // Fibre access hierarchy: switch -> OLT -> passive splitter -> ONT/CPE -> client.
  [["switch-core","HQ",520,600,"10.0.10."],["switch-kawempe","Kawempe",80,525,"10.0.11."],["switch-nansana","Nansana",1020,525,"10.0.12."],["switch-masaka","Masaka",80,850,"10.0.13."],["switch-ntinda","Ntinda",1020,850,"10.0.14."]].forEach(([parent,site,x,y,subnet]) => {
    const prefix=site.toLowerCase(), olt=`${prefix}-olt`, splitter=`${prefix}-splitter`;
    devices.push({id:olt,name:`${site} OLT`,type:"OLT",ip:`${subnet}1`,site,x,y,status:"online",parentId:parent});
    devices.push({id:splitter,name:`${site} FDB / Splitter`,type:"Fiber Splitter",ip:"passive",site,x,y:y+95,status:"online",parentId:olt}); links.push([parent,olt],[olt,splitter]);
    for(let n=1;n<=3;n++){const ont=`${prefix}-ont-${n}`,client=`${prefix}-customer-${n}`,offset=(n-2)*155; devices.push({id:ont,name:`${site} ONT-${String(n).padStart(2,"0")}`,type:"ONT / CPE",ip:`${subnet}${10+n}`,site,x:x+offset,y:y+190,status:"online",parentId:splitter}); devices.push({id:client,name:`${site} Client-${String(n).padStart(2,"0")}`,type:"Client",ip:`${subnet}${100+n}`,site,x:x+offset,y:y+285,status:"online",parentId:ont}); links.push([splitter,ont],[ont,client]);}
  });
  return {devices,links};
}
const seed=makeSeed(); let lab=JSON.parse(localStorage.getItem(STORAGE)||"null")||structuredClone(seed); let selectedId=null; let connectMode=false; let connectFrom=null; let dragState=null; let viewport={x:0,y:0,width:1400,height:1250};
window.addEventListener("storage",event=>{if(event.key!==STORAGE||!event.newValue)return;try{lab=JSON.parse(event.newValue);hydrateVirtualModels();refreshUptimes();draw();}catch(error){console.warn("Unable to sync topology state",error);}});
const icon={Server:"▣",Firewall:"⬢",Router:"◆",Switch:"▦",OLT:"▤","Fiber Splitter":"◇","ONT / CPE":"▥","Access Point":"◉",Client:"▤"};
function save(){localStorage.setItem(STORAGE,JSON.stringify(lab));void window.gssLab.saveInfrastructure?.({devices:lab.devices,links:lab.links});} function selected(){return lab.devices.find(d=>d.id===selectedId);}
function updateViewport(){if(!lab.devices.length)return;const xs=lab.devices.map(d=>Number(d.x)||0),ys=lab.devices.map(d=>Number(d.y)||0);const minX=Math.min(...xs)-250,minY=Math.min(...ys)-180,maxX=Math.max(...xs)+250,maxY=Math.max(...ys)+180;viewport={x:minX,y:minY,width:Math.max(1800,maxX-minX),height:Math.max(1500,maxY-minY)};svg.setAttribute("viewBox",`${viewport.x} ${viewport.y} ${viewport.width} ${viewport.height}`);}
function centerTopology(){if(!canvasWrap)return;const left=svg.offsetLeft+(svg.offsetWidth/2)-(canvasWrap.clientWidth/2),top=svg.offsetTop+(svg.offsetHeight/2)-(canvasWrap.clientHeight/2);canvasWrap.scrollLeft=Math.max(0,left);canvasWrap.scrollTop=Math.max(0,top);}
function applyZoom(){const percent=Math.round(zoom*100);zoomLabel.textContent=`${percent}%`;svg.style.width=`${viewport.width*zoom}px`;svg.style.height=`${viewport.height*zoom}px`;}
function renderInspector(device){if(!device||!deviceInspector||!inspectorContent)return;try{const model=device.model||virtualModel(device,lab.devices.indexOf(device));const health=model.health||{};inspectorContent.innerHTML=`<div class="inspector-title"><h2>${device.name}</h2><p>${device.type} · ${device.site||"Local"} · ${device.status}</p></div><div class="inspector-section"><h3>Device identity</h3><div class="identity-grid"><span>Vendor<b>${model.vendor||"GSS"}</b></span><span>Model<b>${model.model||"Virtual"}</b></span><span>Firmware<b>${model.firmware||"GSS-LabOS 1.0"}</b></span><span>MAC<b>${device.mac||"Not assigned"}</b></span><span>IP address<b>${device.ip}</b></span><span>Device ID<b>${device.id}</b></span></div></div><div class="inspector-section"><h3>Interfaces</h3><table class="interface-table"><thead><tr><th>Interface</th><th>State / speed</th><th>RX / TX</th><th>Errors / drops</th></tr></thead><tbody>${(model.interfaces||[]).map(i=>`<tr><td>${i.name}<small>${i.ip||"—"}</small></td><td>${i.state}<small>${i.speed_mbps||0} Mbps · ${i.duplex||"—"}</small></td><td>${i.rx_packets||0} / ${i.tx_packets||0}<small>${i.rx_bytes||0} / ${i.tx_bytes||0} B</small></td><td>${i.errors||0} / ${i.drops||0}</td></tr>`).join("")}</tbody></table></div><div class="inspector-section"><h3>Health metrics</h3><div class="health-grid"><span>CPU<b>${health.cpu_percent??0}%</b></span><span>Memory<b>${health.memory_percent??0}%</b></span><span>Temperature<b>${health.temperature_c??0}°C</b></span><span>Uptime<b>${health.uptime_seconds??0}s</b></span><span>Status<b>${health.status||device.status}</b></span><span>Traffic RX/TX<b>${model.traffic?.rx_bytes||0} / ${model.traffic?.tx_bytes||0} B</b></span></div></div>`;}catch(error){inspectorContent.textContent=`Unable to render device details: ${error.message||error}`;}deviceInspector.hidden=false;deviceInspector.removeAttribute("hidden");deviceInspector.classList.add("open");}
function virtualModel(d,index){
  if(!d.started_at)d.started_at=Date.now()-(index+1)*3600000;
  const common={vendor:d.type.includes("OLT")?"Huawei":"Cisco",model:d.type==="Router"?"2911":d.type==="Switch"?"2960-24TT":d.type==="Firewall"?"ASA-5505":d.type==="OLT"?"MA5800":"GSS-Virtual",firmware:"GSS-LabOS 1.0",health:{cpu_percent:12,memory_percent:28,temperature_c:34,uptime_seconds:Math.max(0,Math.floor((Date.now()-d.started_at)/1000)),status:"healthy"},traffic:{tx_packets:0,rx_packets:0,tx_bytes:0,rx_bytes:0,errors:0,drops:0},events:[],neighbors:[]};
  const iface=(name,ip,state="up",speed=1000)=>({id:name,name,ip,mac:d.mac,state,speed_mbps:speed,duplex:"full",mtu:1500,rx_packets:0,tx_packets:0,rx_bytes:0,tx_bytes:0,errors:0,drops:0,last_activity:null});
  if(d.type==="Router"){common.interfaces=[iface("GigabitEthernet0/0",d.ip),iface("GigabitEthernet0/1",`10.255.${index+1}.1`),iface("Fiber0/0",`10.255.${index+1}.2`,"up",10000)];common.routing={protocols:["connected","static","OSPF"],routes:[{network:`10.255.${index+1}.0/24`,next_hop:"connected",metric:0},{network:"0.0.0.0/0",next_hop:"10.0.0.1",metric:1}]};}
  else if(d.type==="Switch"){common.interfaces=Array.from({length:24},(_,i)=>iface(`GigabitEthernet0/${i+1}`,"",i<8?"up":"down",1000));common.vlans=[{id:1,name:"default",ports:"1-24"},{id:10,name:"management",ports:"1-2"},{id:20,name:"customers",ports:"3-24"}];common.switching={stp:"forwarding",mac_table:[],trunks:["GigabitEthernet0/1"],access_ports:"GigabitEthernet0/2-24"};}
  else if(d.type==="Firewall"){common.interfaces=[iface("inside",d.ip),iface("outside","203.0.113.1","up",1000),iface("dmz","10.10.0.1","up",1000)];common.firewall={zones:["inside","outside","dmz"],nat:["inside -> outside"],acl:[{action:"allow",source:"inside",destination:"outside",service:"any"}],sessions:0,allowed_traffic:0,blocked_traffic:0};common.routing={routes:[{network:"0.0.0.0/0",next_hop:"203.0.113.254",metric:1}]};}
  else if(d.type==="OLT"){common.interfaces=[iface("uplink",d.ip,"up",10000),...Array.from({length:8},(_,i)=>iface(`PON0/${i+1}`,"","up",2500))];common.pon={profiles:["GPON-1G","GPON-2.5G"],onu_count:0};}
  else if(d.type==="Fiber Splitter"){common.interfaces=[iface("PON-IN","passive","up",2500),iface("PON-OUT","passive","up",2500)];common.passive=true;}
  else {common.interfaces=[iface("Ethernet0",d.ip,"up",1000),iface("WiFi0","","up",300)];}
  return common;
}
function hydrateVirtualModels(){lab.devices.forEach((d,index)=>{if(!d.model)d.model=virtualModel(d,index);d.model.neighbors=lab.links.filter(([a,b])=>a===d.id||b===d.id).map(([a,b])=>a===d.id?b:a);});}
function refreshUptimes(){const now=Date.now();lab.devices.forEach((d,index)=>{if(!d.started_at)d.started_at=now-(index+1)*3600000;if(d.model?.health)d.model.health.uptime_seconds=Math.max(0,Math.floor((now-d.started_at)/1000));});}
function ensureNetworkIdentity(){lab.devices.forEach((d,index)=>{if(!d.ip||d.ip==="unknown"||d.ip==="passive")d.ip=`10.255.${Math.floor(index/240)+1}.${(index%240)+10}`;if(!d.mac)d.mac=`02:47:${((index+1)>>8&255).toString(16).padStart(2,"0")}:${((index+1)&255).toString(16).padStart(2,"0")}:55:${(index%99).toString(16).padStart(2,"0")}`.toUpperCase();if(!d.started_at)d.started_at=Date.now()-(index+1)*3600000;});hydrateVirtualModels();refreshUptimes();save();}
function setServerState(running,message){serverStartBtn.disabled=running;serverStopBtn.disabled=!running;serverStatus.textContent=message;}
function renderCloudStatus(status){if(!cloudStatus)return;const online=status?.state==="synced";const checking=status?.state==="syncing"||status?.state==="waiting";cloudStatus.textContent=status?.message||"Cloud telemetry status unavailable.";cloudSaveBtn.textContent=status?.configured?"Update cloud key":"Save cloud key";if(cloudConnectionDot)cloudConnectionDot.className=online?"online":checking?"checking":"offline";if(cloudConnectionState)cloudConnectionState.textContent=online?"GSS Cloud: Online":status?.state==="waiting"?"GSS Cloud: Waiting for plan interval":checking?"GSS Cloud: Checking…":"GSS Cloud: Offline";}
function showScreen(screen){const topology=screen==="topology";layout.classList.toggle("mode-topology",topology);layout.classList.toggle("mode-management",!topology);topologyScreenBtn.classList.toggle("active",topology);managementScreenBtn.classList.toggle("active",!topology);}
const windowScreen=new URLSearchParams(window.location.search).get("screen");
if(windowScreen==="management"){document.body.classList.add("management-window");showScreen("management");}
if(windowScreen==="topology") document.body.classList.add("topology-window");
if(windowScreen==="traffic"){document.body.classList.add("traffic-window");document.getElementById("trafficScreen").hidden=false;}
function updateLinks(){const byId=Object.fromEntries(lab.devices.map(d=>[d.id,d]));svg.querySelectorAll("line.link").forEach(line=>{const a=byId[line.dataset.a],b=byId[line.dataset.b];if(a&&b){line.setAttribute("x1",a.x);line.setAttribute("y1",a.y);line.setAttribute("x2",b.x);line.setAttribute("y2",b.y);}});}
function onlineReachable(){const root=lab.devices.find(d=>d.id==="gss-server"||d.type==="Server");if(!root||root.status==="offline")return new Set();const reachable=new Set([root.id]);let changed=true;while(changed){changed=false;lab.links.forEach(([a,b])=>{const left=lab.devices.find(d=>d.id===a),right=lab.devices.find(d=>d.id===b);if(!left||!right||left.status==="offline"||right.status==="offline")return;if(reachable.has(a)&&!reachable.has(b)){reachable.add(b);changed=true;}if(reachable.has(b)&&!reachable.has(a)){reachable.add(a);changed=true;}});}return reachable;}
function draw(){
  if(lab.devices.some(d=>!d.mac||!d.model)) ensureNetworkIdentity();
  refreshUptimes();
  updateViewport();
  applyZoom();
  const byId=Object.fromEntries(lab.devices.map(d=>[d.id,d]));
  const links=lab.links.map(([a,b])=>{const x=byId[a],y=byId[b];return x&&y?`<line class="link ${x.status==="offline"||y.status==="offline"?"down":""}" data-a="${a}" data-b="${b}" x1="${x.x}" y1="${x.y}" x2="${y.x}" y2="${y.y}" />`:"";}).join("");
  const nodes=lab.devices.map(d=>`<g class="node ${d.status==="offline"?"down":d.status==="degraded"?"warn":""} ${d.id===selectedId?"selected":""}" data-id="${d.id}" transform="translate(${d.x-70},${d.y-34})"><rect class="body" width="140" height="68"/><rect class="tap-zone" x="32" y="4" width="76" height="43" rx="4"/><text class="glyph" x="70" y="23" font-size="20">${icon[d.type]||"◆"}</text><text x="70" y="42">${d.name}</text><text class="ip" x="70" y="57">${d.ip}</text><circle class="port" cx="8" cy="34" r="4"/><circle class="port" cx="132" cy="34" r="4"/></g>`).join("");
  svg.innerHTML=`<text x="28" y="35" fill="#69808f" font-size="12" letter-spacing="2">GSS LOCAL FIBRE TOPOLOGY · REAL DEVICE ADDRESSES</text>${links}${nodes}`;
  svg.querySelectorAll(".node").forEach(el=>{
    el.addEventListener("click",()=>{const id=el.dataset.id;if(connectMode){if(!connectFrom){connectFrom=id;selection.textContent=`Connect from ${lab.devices.find(d=>d.id===id)?.name} · tap a second device`;return;}if(connectFrom!==id&&!lab.links.some(([a,b])=>(a===connectFrom&&b===id)||(a===id&&b===connectFrom))){lab.links.push([connectFrom,id]);save();}connectFrom=null;connectMode=false;connectBtn.classList.remove("active");connectBtn.textContent="Connect devices";draw();select(id);return;}select(id);});
    el.addEventListener("pointerdown",event=>{if(connectMode)return;const d=lab.devices.find(x=>x.id===el.dataset.id);dragState={d,startX:event.clientX,startY:event.clientY,originX:d.x,originY:d.y,el,moved:false};el.setPointerCapture?.(event.pointerId);});
    el.addEventListener("pointermove",event=>{if(!dragState||dragState.d!==lab.devices.find(x=>x.id===el.dataset.id))return;const dx=(event.clientX-dragState.startX)*1.2,dy=(event.clientY-dragState.startY)*1.2;if(Math.abs(dx)>4||Math.abs(dy)>4)dragState.moved=true;dragState.d.x=dragState.originX+dx;dragState.d.y=dragState.originY+dy;dragState.el.setAttribute("transform",`translate(${dragState.d.x-70},${dragState.d.y-34})`);updateLinks();});
    el.addEventListener("pointerup",()=>{if(!dragState)return;const state=dragState;dragState=null;if(state.moved){save();draw();}else{select(state.d.id);}}); const tapZone=el.querySelector(".tap-zone"); tapZone?.addEventListener("pointerdown",event=>{event.stopPropagation();}); tapZone?.addEventListener("click",event=>{event.stopPropagation();select(el.dataset.id);});
  });
  list.innerHTML=lab.devices.map(d=>`<div class="device-row ${d.id===selectedId?"selected":""}" data-id="${d.id}"><i class="device-dot ${d.status==="offline"?"down":d.status==="degraded"?"warn":""}"></i><div><b>${d.name}</b><small>${d.type} · ${d.ip}${d.mac?` · ${d.mac}`:""}</small></div></div>`).join("");
  list.querySelectorAll(".device-row").forEach(el=>el.addEventListener("click",()=>select(el.dataset.id)));
  parentField.innerHTML=`<option value="">Standalone / core device</option>`+lab.devices.filter(d=>["Switch","OLT","Fiber Splitter","ONT / CPE"].includes(d.type)).map(d=>`<option value="${d.id}">${d.name} · ${d.ip}</option>`).join(""); if(selectedId)parentField.value=selectedId;
}
function renderConnectionControls(device){if(!inspectorContent||!device)return;inspectorContent.querySelector(".connection-controls")?.remove();const section=document.createElement("div");section.className="inspector-section connection-controls";section.innerHTML=`<h3>Connection control</h3><p class="inspector-help">Change the simulated management/link state for this device.</p><div class="inspector-actions"><button type="button" data-connection-action="disconnect" ${device.status==="offline"?"disabled":""}>Disconnect</button><button type="button" data-connection-action="reconnect" ${device.status!=="offline"?"disabled":""}>Reconnect</button></div>`;inspectorContent.appendChild(section);}
inspectorContent?.addEventListener("click",async event=>{const button=event.target.closest("[data-connection-action]");if(!button)return;const device=selected();if(!device)return;const online=button.dataset.connectionAction==="reconnect";device.status=online?"online":"offline";const model=device.model||virtualModel(device,lab.devices.indexOf(device));device.model=model;model.health.status=online?"healthy":"offline";model.interfaces?.forEach(iface=>{if(iface.ip!=="passive")iface.state=online?"up":"down";});model.events.unshift({time:new Date().toISOString(),type:"connection",message:`${online?"Reconnected":"Disconnected"} by local operator`});await window.gssLab.updateDeviceStatus?.(device.id,device.status);save();draw();renderInspector(device);renderConnectionControls(device);});
function select(id){selectedId=id;const d=selected();selection.textContent=d?`${d.name} · ${d.type} · ${d.ip}`:"No device selected";pingBtn.disabled=!d;agentBtn.disabled=!d;agentStatus.textContent=d?`Selected ${d.name}. The local test runs from this computer.`:"Select a device and run a local ICMP test.";if(!d&&deviceInspector){deviceInspector.hidden=true;deviceInspector.classList.remove("open");}draw();if(d){renderInspector(d);renderConnectionControls(d);}if(d&&["Switch","OLT","Fiber Splitter","ONT / CPE"].includes(d.type))parentField.value=d.id;}
document.querySelectorAll(".panel-toggle").forEach(toggle=>{toggle.addEventListener("click",()=>{const panel=toggle.nextElementSibling;const open=panel.hidden;panel.hidden=!open;toggle.setAttribute("aria-expanded",String(open));toggle.querySelector(".chevron").textContent=open?"−":"+";});});
document.getElementById("zoomIn")?.addEventListener("click",()=>{zoom=Math.min(2.5,zoom+0.1);applyZoom();}); document.getElementById("zoomOut")?.addEventListener("click",()=>{zoom=Math.max(0.1,zoom-0.1);applyZoom();}); document.getElementById("zoomFit")?.addEventListener("click",()=>{const width=Math.max(320,canvasWrap?.clientWidth||window.innerWidth);const height=Math.max(240,canvasWrap?.clientHeight||window.innerHeight);zoom=Math.max(0.1,Math.min(2.5,(width-40)/viewport.width,(height-40)/viewport.height));applyZoom();centerTopology();}); document.getElementById("zoomReset")?.addEventListener("click",()=>{zoom=1;applyZoom();centerTopology();}); canvasWrap?.addEventListener("wheel",event=>{if(event.target.closest("#deviceInspector,#zoomControls"))return;event.preventDefault();zoom=Math.max(0.1,Math.min(2.5,zoom+(event.deltaY<0?0.1:-0.1)));applyZoom();},{passive:false});
const closeInspector=document.getElementById("closeInspector"); const closeInspectorPanel=(event)=>{event.preventDefault();event.stopImmediatePropagation();selectedId=null;deviceInspector.hidden=true;deviceInspector.removeAttribute("open");deviceInspector.classList.remove("open");}; ["pointerdown","mousedown","pointerup","click"].forEach(type=>closeInspector?.addEventListener(type,closeInspectorPanel,true));
topologyScreenBtn.addEventListener("click",()=>showScreen("topology")); managementScreenBtn.addEventListener("click",()=>showScreen("management"));
window.gssLab.cloudStatus?.().then(renderCloudStatus).catch(()=>renderCloudStatus());
window.gssLab.onCloudStatus?.(renderCloudStatus);
window.gssLab.loadInfrastructure?.().then(saved=>{if(Array.isArray(saved?.devices)&&saved.devices.length&&Array.isArray(saved.links)){lab={devices:saved.devices,links:saved.links};hydrateVirtualModels();localStorage.setItem(STORAGE,JSON.stringify(lab));draw();}}).catch(()=>{});
cloudSaveBtn?.addEventListener("click",async()=>{const key=cloudApiKey.value.trim();cloudSaveBtn.disabled=true;const result=await window.gssLab.configureCloud(key);cloudSaveBtn.disabled=false;if(!result.ok){renderCloudStatus({message:result.error||"Unable to save the cloud key."});return;}cloudApiKey.value="";renderCloudStatus(result);});
connectBtn.addEventListener("click",()=>{connectMode=!connectMode;connectFrom=null;connectBtn.classList.toggle("active",connectMode);connectBtn.textContent=connectMode?"Tap two devices · cancel":"Connect devices";selection.textContent=connectMode?"Connection mode · tap the first device":"No device selected";});
serverStartBtn.addEventListener("click",async()=>{ensureNetworkIdentity();const result=await window.gssLab.startLocalServer({devices:lab.devices,links:lab.links});const assigned=Object.fromEntries((result.devices||[]).map(d=>[d.id,d.ip]));lab.devices.forEach(d=>{if(assigned[d.id]){d.ip=assigned[d.id];const iface=d.model?.interfaces?.find(i=>i.ip&&i.ip!=="passive");if(iface)iface.ip=d.ip;}});save();setServerState(true,`Running on ${result.url}. PC server IP: ${result.host}. Virtual devices received randomized lab addresses.`);draw();});
serverStopBtn.addEventListener("click",async()=>{await window.gssLab.stopLocalServer();setServerState(false,"The PC server is stopped. Start it to resume local traffic.");});
window.gssLab.onTraffic((packet)=>{
  const byId=Object.fromEntries(lab.devices.map(d=>[d.id,d])); const source=byId[packet.a], target=byId[packet.b];
  const reachable=onlineReachable();
  if(!source||!target||!reachable.has(source.id)||!reachable.has(target.id))return;
  if(source&&target){const tx=source.model||virtualModel(source,lab.devices.indexOf(source));const rx=target.model||virtualModel(target,lab.devices.indexOf(target));source.model=tx;target.model=rx;tx.traffic.tx_packets++;tx.traffic.tx_bytes+=packet.bytes;rx.traffic.rx_packets++;rx.traffic.rx_bytes+=packet.bytes;const txIndex=Math.max(0,(tx.neighbors||[]).indexOf(target.id))%Math.max(1,tx.interfaces?.length||1),rxIndex=Math.max(0,(rx.neighbors||[]).indexOf(source.id))%Math.max(1,rx.interfaces?.length||1),txIface=tx.interfaces?.[txIndex],rxIface=rx.interfaces?.[rxIndex];if(txIface){txIface.tx_packets++;txIface.tx_bytes+=packet.bytes;txIface.last_activity=new Date().toISOString();txIface.state=source.status==="offline"?"down":"up";}if(rxIface){rxIface.rx_packets++;rxIface.rx_bytes+=packet.bytes;rxIface.last_activity=new Date().toISOString();rxIface.state=target.status==="offline"?"down":"up";}if(selectedId===source.id||selectedId===target.id){renderInspector(selected());renderConnectionControls(selected());}}
  if(windowScreen==="traffic"&&source&&target){const log=document.getElementById("trafficLog"),count=document.getElementById("trafficCount");const row=document.createElement("div");row.innerHTML=`<small>${new Date().toLocaleTimeString()}</small>RX ${packet.bytes} B · ${target.name} · ${target.ip}  ←  ${source.name} · ${source.ip}`;log.prepend(row);while(log.children.length>120)log.lastElementChild.remove();count.textContent=`${log.children.length} packets`;}
  const line=[...svg.querySelectorAll("line.link")].find(el=>(el.dataset.a===packet.a&&el.dataset.b===packet.b)||(el.dataset.a===packet.b&&el.dataset.b===packet.a));
  if(!line||!source||!target)return;
  line.classList.add("traffic"); setTimeout(()=>line.classList.remove("traffic"),500);
  const circle=document.createElementNS("http://www.w3.org/2000/svg","circle"); circle.setAttribute("class","packet"); circle.setAttribute("r","6"); circle.setAttribute("cx",source.x); circle.setAttribute("cy",source.y);
  const move=document.createElementNS("http://www.w3.org/2000/svg","animate"); move.setAttribute("attributeName","cx"); move.setAttribute("from",source.x); move.setAttribute("to",target.x); move.setAttribute("dur","0.45s"); move.setAttribute("fill","freeze"); circle.appendChild(move);
  const moveY=document.createElementNS("http://www.w3.org/2000/svg","animate"); moveY.setAttribute("attributeName","cy"); moveY.setAttribute("from",source.y); moveY.setAttribute("to",target.y); moveY.setAttribute("dur","0.45s"); moveY.setAttribute("fill","freeze"); circle.appendChild(moveY); svg.appendChild(circle); move.beginElement(); moveY.beginElement(); setTimeout(()=>circle.remove(),550);
  setTimeout(()=>{const node=svg.querySelector(`.node[data-id="${packet.b}"]`);if(node){node.classList.add("receiving");setTimeout(()=>node.classList.remove("receiving"),430);}const feed=document.getElementById("trafficFeed");if(feed){const row=document.createElement("div");row.textContent=`RX ${packet.bytes} B · ${target.name} · ${target.ip}`;feed.prepend(row);setTimeout(()=>row.remove(),2200);}},430);
});
document.getElementById("deviceForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name")||`${String(f.get("type"))} ${lab.devices.length+1}`),type=String(f.get("type")),parentId=String(f.get("parent")||""),parent=lab.devices.find(d=>d.id===parentId),id=name.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now().toString(36),x=parent?parent.x+(Math.random()>.5?170:-170):700+Math.round(Math.random()*180-90),y=parent?parent.y+105:500+Math.round(Math.random()*180-90),device={id,name,type,ip:String(f.get("ip")||""),site:String(f.get("site")||parent?.site||"Local"),x,y,status:"online",parentId,started_at:Date.now(),model:null};lab.devices.push(device);if(parent)lab.links.push([parent.id,id]);ensureNetworkIdentity();save();e.currentTarget.reset();select(id);});
pingBtn.addEventListener("click",async()=>{const d=selected();if(!d)return;agentStatus.textContent=`Pinging ${d.ip}…`;const result=await window.gssLab.ping(d.ip);d.status=result.ok?"online":"offline";save();draw();agentStatus.textContent=result.ok?`${d.name} reachable · ${result.latencyMs} ms`:`${d.name} did not respond`;}); agentBtn.addEventListener("click",()=>{const d=selected();if(d)agentStatus.textContent=`Agent test queued for ${d.name}. Install GSSAgent on the main server, then use this address as the monitored target.`;});
document.getElementById("resetBtn").addEventListener("click",()=>{lab=makeSeed();selectedId=null;save();draw();select(null);centerTopology();}); setInterval(()=>document.getElementById("clock").textContent=new Date().toLocaleTimeString(),1000); draw(); setTimeout(centerTopology,80);
